-- Tabela Categories
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela Subcategories
CREATE TABLE public.subcategories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela Products
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    image TEXT,
    price REAL,
    price_original REAL,
    keywords TEXT,
    link_afiliado TEXT,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    subcategory_id BIGINT REFERENCES public.subcategories(id) ON DELETE SET NULL,
    clicks INTEGER DEFAULT 0,
    featured INTEGER DEFAULT 0,
    tag_label TEXT,
    tag_color TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela Users
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    is_admin INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela Clicks Log
CREATE TABLE public.clicks_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Inserindo o Usuário Mestre (Senha = TopFinds@2026 hashada com bcrypt)
INSERT INTO public.users (name, email, password, is_admin)
VALUES ('Administrador Mestre', 'topfinds.dj2@gmail.com', '$2a$10$tZkKk4Z5XyZ2Pq/S4EwqOee5z36F.m1.QnB09O6uG50U77Oq/W706', 1);

-- Ativando RLS mas permitindo todas as operações (para testes, pode ser refinado dps)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subcategories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clicks_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all operations for all users" ON public.categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for all users" ON public.subcategories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for all users" ON public.products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for all users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for all users" ON public.clicks_log FOR ALL USING (true) WITH CHECK (true);
